scaling

In [1]:
import cv2
import matplotlib.pyplot as plt

img = cv2.imread('NAO.jpg')
img_scaled = cv2.resize(img,None,fx=0.5,fy=0.5,interpolation=cv2.INTER_LINEAR)
#INTERLINEAR for shrinking, INTERAREA,INTERCUBIC for stretching
print(img.shape)
print(img_scaled.shape)
#zooming and interpolation are different
#Zooming refers to increase the quantity of pixels, so that when you zoom an image, you will see more detail.
# Interpolation works by using known data to estimate values at unknown points.

(639, 480, 3)
(320, 240, 3)


affine transformation

In [ ]:
#affine transformation mtlb pixel position manipulation...color not changed
#Affine transformation is a linear mapping method that preserves points, straight lines, and planes. 
#Sets of parallel lines remain parallel after an affine transformation

In [2]:
import numpy as np

In [3]:
num_rows, num_cols = img.shape[:2]
src_points = np.float32([[0,0],[num_cols-1,0],[0,num_rows-1],[num_cols-1,num_rows-1]])
 #number of columns pehle likha jata h

In [4]:
src_points

array([[  0.,   0.],
       [479.,   0.],
       [  0., 638.],
       [479., 638.]], dtype=float32)

In [5]:
img.shape

(639, 480, 3)

In [6]:
dst_points=np.float32([[0,0],[num_cols-1,0],[int(0.3*num_cols),num_rows-1],[int(0.6*num_cols),num_rows-1]])

In [7]:
dst_points

array([[  0.,   0.],
       [479.,   0.],
       [144., 638.],
       [288., 638.]], dtype=float32)

In [8]:
project_matrix = cv2.getPerspectiveTransform(src_points,dst_points)

In [9]:
project_matrix

array([[ 1.        ,  0.7507837 ,  0.        ],
       [ 0.        ,  3.32638889,  0.        ],
       [-0.        ,  0.00364638,  1.        ]])

In [10]:
img_out = cv2.warpPerspective(img,project_matrix,(num_cols,num_rows))

In [11]:
cv2.imwrite("res.jpg",img_out)

True

In [ ]:
#horizontal perspective

In [12]:
import numpy as np
import cv2
img = cv2.imread('NAO.jpg')
num_rows, num_cols = img.shape[:2]
src_points = np.float32([[0,0],[num_cols-1,0],[0,num_rows-1],[num_cols-1,num_rows-1]])
dst_points=np.float32([[0,int(0.3*num_rows)],[num_cols-1,0],[0,int(0.6*num_rows)],[num_cols-1,num_rows-1]])
project_matrix = cv2.getPerspectiveTransform(src_points,dst_points)
img_out = cv2.warpPerspective(img,project_matrix,(num_cols,num_rows))
cv2.imwrite("res_horizontal.jpg",img_out)


True

In [13]:
import numpy as np
import math

img = cv2.imread("NAO.jpg",cv2.IMREAD_GRAYSCALE)
rows,cols = img.shape
img_output = np.zeros(img.shape)
for i in range(rows):
    for j in range(cols):
        
        
        offset_x = int(80.0*math.sin(2*3.148*i/180))
        offset_y = 0

        if j+offset_x < cols:
            img_output[i,j] = img[i,(j+offset_x)]
        else:
             img_output[i,j] = 0
                
cv2.imwrite("sinres.jpg",img_output)               

True

In [14]:
import numpy as np
import math

img = cv2.imread("NAO.jpg",cv2.IMREAD_GRAYSCALE)
rows,cols = img.shape
img_output = np.zeros(img.shape)
for i in range(rows):
    for j in range(cols):
        
        
        offset_y = int(80.0*math.sin(2*3.148*j/180))
        offset_x = 0

        if i+offset_y < rows:
            img_output[i,j] = img[(i+offset_y),j]
        else:
             img_output[i,j] = 0
                
cv2.imwrite("sinreshorizontal.jpg",img_output)               

True